# Generated by Django 5.2.4 on 2025-08-04 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('distance_mly', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlackHole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('mass_solar', models.FloatField()),
                ('distance_from_center_ly', models.FloatField()),
                ('description', models.TextField()),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackholes', to='pokedex.galaxy')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('mass_solar', models.FloatField()),
                ('radius_solar', models.FloatField()),
                ('description', models.TextField()),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='pokedex.galaxy')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('mass_earth', models.FloatField()),
                ('radius_earth', models.FloatField()),
                ('habitable', models.BooleanField(default=False)),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='pokedex.galaxy')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='pokedex.star')),
            ],
        ),
    ]
