# Generated by Django 5.2.4 on 2025-07-24 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('power', models.IntegerField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pokedex_num', models.IntegerField(unique=True)),
                ('does_evolve', models.BooleanField(default=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('base_stats', models.JSONField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('base_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_evolution', to='pokedex.pokemon')),
                ('evolved_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolves_to', to='pokedex.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(through='pokedex.PokemonMove', to='pokedex.move'),
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.type')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(through='pokedex.PokemonType', to='pokedex.type'),
        ),
        migrations.AddField(
            model_name='move',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='pokedex.type'),
        ),
    ]
